name: CI Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      # Étape 1 — Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 — Installer Java 21
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Étape 3 — Cache Maven
      # Sans ça : 200Mo téléchargés à chaque push
      # Avec ça : téléchargé une fois, mis en cache
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Étape 4 — Compiler + Tester + Builder en une commande
      # mvn verify = compile + test + package
      - name: Build and Test
        run: mvn verify --no-transfer-progress

      # Étape 5 — Publier les résultats de tests
      # Visible dans l'onglet "Actions" de GitHub
      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JUnit Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit